const text = [
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam cursus, risus sit amet euismod hendrerit, metus sem egestas ante, in pretium lectus magna in urna. Donec id dignissim tortor. Aliquam erat volutpat. Curabitur ornare mi sed eros tempus ornare. Phasellus mattis feugiat arcu sed dapibus. Phasellus elementum nunc imperdiet ex dictum tempor. Nullam vitae diam dictum tortor hendrerit viverra. Integer eget tincidunt tellus, eget gravida magna. Nulla nec neque nec nibh cursus tempus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam iaculis rhoncus tincidunt.",

  "In leo mauris, convallis nec fringilla nec, consectetur varius nulla. In rhoncus scelerisque risus, sit amet maximus orci lacinia in. Phasellus suscipit vel risus id gravida. Donec imperdiet viverra hendrerit. Phasellus et libero justo. Praesent non bibendum sem, quis viverra sem. Etiam fermentum molestie enim. Maecenas sollicitudin vitae lacus dignissim venenatis. Nullam iaculis ut enim vel elementum. Sed consequat ut diam vitae tristique. Duis et mi et metus porta ultrices id a ex. Suspendisse a ex in felis auctor porta a sit amet nibh. Sed sit amet massa laoreet, aliquet ipsum aliquet, aliquam velit. Ut cursus pulvinar massa quis blandit. Donec maximus ante eget justo suscipit, eget malesuada lectus maximus. Sed vel diam at nisi vestibulum scelerisque eget a nisl.",

  "Donec aliquet sagittis nunc eu tincidunt. Donec velit odio, volutpat ut placerat nec, lobortis eget eros. Etiam lacinia id dui eu pharetra. Nam posuere lacus non nisl consequat, et pharetra velit aliquam. Quisque aliquet ipsum et pellentesque tincidunt. Mauris sit amet metus venenatis, vulputate lacus eu, pulvinar massa. Curabitur odio nisl, convallis nec lectus sed, congue pharetra sapien. Vestibulum arcu ex, consectetur finibus convallis a, aliquam hendrerit ipsum.",

  "Suspendisse potenti. Aliquam lacinia dui sit amet placerat facilisis. Nam non ullamcorper orci. Sed gravida, metus eleifend fringilla pellentesque, leo tellus ullamcorper sapien, vitae consequat dolor metus at felis. Aenean malesuada eros lacinia libero suscipit tristique vitae eu quam. Aliquam erat volutpat. Sed iaculis, libero ac vehicula posuere, quam diam pretium metus, et semper felis lacus nec odio. Fusce iaculis, velit ullamcorper ultricies tristique, diam tellus dignissim dui, sit amet scelerisque felis quam eu nisi. Pellentesque varius quam urna, efficitur imperdiet elit lobortis eu. Praesent ullamcorper interdum cursus. Ut vitae sapien fermentum, semper augue quis, tincidunt elit.",

  "Maecenas lectus dui, scelerisque in posuere sed, commodo vitae ante. Duis euismod magna efficitur accumsan tincidunt. Aenean pretium gravida laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nulla ultricies dui at ex suscipit, ornare aliquam arcu varius. Sed orci neque, vestibulum sit amet dapibus facilisis, imperdiet eu ex. Aliquam erat volutpat. Praesent rhoncus ante a metus dictum finibus. Vestibulum vestibulum, erat a pretium laoreet, mi nisi commodo justo, eget gravida quam elit eu neque. Nam tincidunt ligula in metus auctor mattis. Etiam vulputate turpis non orci porttitor interdum.",

  "Curabitur sed lectus consequat, rutrum metus at, viverra est. Cras vitae elit ut neque semper ullamcorper. Etiam malesuada neque id nisi laoreet, sollicitudin convallis lectus convallis. Mauris a sapien et velit sollicitudin iaculis at non mauris. Phasellus sodales sem ac nisi fermentum semper. Morbi pharetra commodo purus, vitae finibus turpis tincidunt eu. Cras elementum, ligula ut tincidunt imperdiet, dolor sapien pellentesque dui, at malesuada sapien velit sit amet sapien.",

  "Donec tellus sem, dictum sed aliquam sit amet, ultricies id odio. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Morbi id risus et turpis ornare tempus. Nam malesuada neque quis massa egestas, ut consectetur est rhoncus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sit amet aliquet ex. Morbi quis arcu in nisl vestibulum imperdiet. Morbi efficitur justo auctor odio scelerisque dapibus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris at diam porttitor, fringilla nunc consequat, ultricies lorem. Pellentesque vel felis dictum nulla pretium pulvinar. Maecenas sed augue at lacus facilisis elementum vitae ac nulla.",

  "Sed euismod, mauris id posuere rutrum, eros leo convallis risus, sit amet vulputate tortor lacus et metus. Cras semper dui in rutrum tempor. Nunc congue erat at tincidunt facilisis. Nulla facilisi. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nam malesuada elit facilisis ligula lobortis sollicitudin. In hac habitasse platea dictumst. In pellentesque porttitor imperdiet. Etiam consectetur porttitor ornare. Fusce quis porta mi. Curabitur ante ligula, interdum id mi vel, tincidunt vehicula eros.",

  "Sed nec porta enim, eget rhoncus massa. Quisque lobortis est ornare eros blandit aliquam. Ut imperdiet ante sit amet risus ornare auctor ut nec sem. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sed eleifend diam. Fusce vel lectus id massa feugiat cursus. Morbi sed nunc lorem. Aliquam pretium nulla eu ipsum auctor lacinia. Sed volutpat tincidunt orci, non mattis mi placerat ut. Donec eu nunc dui. Nunc sed efficitur diam.",

  "Nulla aliquet, odio a laoreet dapibus, est nisi dignissim eros, eu aliquam turpis dui ut risus. Donec nec dictum urna. Praesent sit amet pulvinar ligula. Phasellus feugiat, nibh eget lacinia luctus, nibh nibh imperdiet ante, in porta diam erat sit amet neque. Nullam quis venenatis leo. Ut dictum odio quis turpis pulvinar, in hendrerit quam feugiat. Donec placerat dolor nec pellentesque elementum. Duis vel ultricies metus. Nunc eu lacus tempus, sodales sem ac, vulputate mauris. Cras sed pellentesque magna. Phasellus fringilla sodales felis, in consectetur quam eleifend ac. Donec egestas vulputate est, ut elementum sem dapibus ut. Phasellus gravida vehicula leo sit amet vulputate. Integer tincidunt sem id magna semper dapibus. Pellentesque eget orci scelerisque, interdum nibh eu, placerat turpis.",

  "Curabitur pulvinar lacus sed tempus molestie. Aenean faucibus malesuada libero ut tincidunt. Integer porta metus in felis porta, eu mattis libero porta. In id augue et erat vehicula dictum eget id dui. Praesent rhoncus semper nulla vitae vehicula. Etiam neque ligula, tempor eu dictum quis, ornare vitae purus. Duis sit amet viverra neque, eget feugiat sapien.",

  "Vestibulum eu libero dolor. Vestibulum mattis luctus elit, nec vestibulum arcu tincidunt ut. Vestibulum laoreet magna a euismod mollis. In hac habitasse platea dictumst. Duis cursus libero eget leo rutrum, nec bibendum nulla tincidunt. Donec malesuada odio ac velit suscipit rhoncus. Nam finibus leo sit amet mollis rhoncus. Quisque sed diam dui. Phasellus mauris metus, scelerisque sit amet dignissim nec, tristique vel lectus. Aenean varius nisi id tellus vehicula, at eleifend ante dapibus. Etiam sed lectus et mi blandit ultrices.",

  " Nulla aliquet volutpat lorem, ac ultricies enim condimentum vel. Suspendisse tincidunt aliquet orci, ut condimentum nulla condimentum sed. Nam gravida vitae dolor vehicula elementum. Ut blandit arcu leo, sit amet pretium leo auctor et. Phasellus eleifend sodales eleifend. Nunc rhoncus urna sed odio dapibus blandit. Etiam a velit ligula. Phasellus auctor lorem quis sem varius, at viverra orci imperdiet. Donec sem augue, dictum rutrum magna ac, imperdiet posuere mauris. Mauris vel fringilla purus. Vivamus sem nulla, feugiat nec bibendum sed, vulputate nec tellus. Vivamus tempus leo ipsum, sit amet vulputate sem ultricies ac. Nulla tristique nec leo et aliquet.",

  "Suspendisse vitae scelerisque odio. Cras ultricies nec risus vel ornare. Aenean ornare semper magna. Pellentesque justo ex, ultrices in leo venenatis, elementum maximus turpis. Sed euismod pharetra arcu eu condimentum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Suspendisse potenti.",

  "Donec eu leo turpis. Aenean iaculis id lectus in feugiat. Sed condimentum ullamcorper sapien in porta. Sed mollis cursus sagittis. Ut faucibus sapien sit amet mauris ultrices, nec commodo elit faucibus. Donec eu neque aliquet, scelerisque metus sed, ornare lectus. Nullam erat justo, efficitur nec felis nec, faucibus auctor urna. Nam neque nunc, rhoncus id nulla quis, elementum iaculis justo. Morbi sollicitudin imperdiet sapien, a iaculis orci sodales non.",

  "Nullam suscipit ex velit, et ornare ex tincidunt eget. Duis elit turpis, lacinia id fringilla eget, dapibus sed ipsum. Quisque auctor eros eget egestas maximus. Integer consequat, justo sit amet dapibus bibendum, quam mauris blandit justo, eget volutpat felis leo a lectus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce quis ultrices purus, vel finibus eros. Praesent ut turpis eu eros eleifend auctor. Nam sodales lectus ac nulla suscipit, id iaculis nunc consectetur. Aenean finibus pulvinar mattis. Phasellus pharetra fermentum tristique. Curabitur elementum gravida mauris eu blandit. Proin faucibus, lorem a euismod ornare, felis risus aliquam magna, vel mattis libero ipsum at urna. Cras mollis nisl pretium orci imperdiet consequat. Integer imperdiet mi ut ullamcorper aliquet. Sed sollicitudin, mi vitae ultricies porta, erat mauris gravida dolor, vitae condimentum lectus orci id ex. Sed nec turpis nisl.",

  "Nunc consectetur orci at ante consectetur hendrerit. Quisque vel dui metus. Sed elementum sodales massa, vitae lobortis ipsum viverra eget. Vivamus malesuada molestie tortor nec elementum. Vestibulum quis orci erat. Donec rhoncus rutrum turpis, et rhoncus metus pellentesque eu. Pellentesque fringilla, enim sed interdum tempor, sapien ipsum vulputate lorem, ac viverra risus neque quis purus. Proin dolor odio, ullamcorper non interdum in, euismod quis elit. Vivamus ornare, mi in consectetur sodales, massa augue suscipit urna, quis facilisis diam eros eget sapien. Etiam posuere odio at erat fringilla consectetur. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec dapibus justo tellus, venenatis finibus augue feugiat eu. Donec non varius urna. Sed in dignissim odio.",

  "Proin dui ligula, viverra ac rutrum bibendum, fermentum id nisi. Praesent mollis congue leo eget porta. Maecenas sit amet elit nec turpis aliquet iaculis at at diam. Suspendisse egestas nisi at neque ultrices, a suscipit magna ornare. Mauris iaculis lorem at nulla hendrerit cursus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla facilisi. Quisque laoreet posuere blandit. Donec tincidunt ipsum et urna molestie pretium. Vivamus pellentesque lorem vitae tellus ultrices ultrices. Cras congue tortor risus. Pellentesque semper leo nec est laoreet, vitae tempus mi blandit. Aliquam velit leo, bibendum in odio at, molestie imperdiet nulla.",

  "Curabitur ac eros a purus sagittis feugiat. Maecenas et turpis nibh. Phasellus sapien nisi, malesuada a euismod vitae, congue non purus. Praesent vestibulum maximus sem, vulputate dictum dolor sodales a. Mauris nec ornare odio. Nam in luctus ligula. Integer sagittis, ex sed suscipit finibus, dolor risus viverra nulla, auctor blandit quam velit nec nisl. Etiam vel ligula tempor, ultrices erat non, viverra tortor.",

  "Cras non mi ac enim viverra feugiat. Aenean feugiat vel velit ac scelerisque. Praesent aliquet, lacus sodales cursus pellentesque, lorem libero convallis leo, quis placerat dolor purus a urna. Pellentesque in turpis enim. Vestibulum ut diam placerat, vulputate arcu accumsan, mollis neque. Aenean pellentesque ornare arcu, nec cursus risus efficitur eu. Ut tincidunt in eros quis viverra. In nec varius sem. Fusce lobortis ante sit amet elit volutpat, sit amet aliquet risus congue. In nibh mi, accumsan sit amet laoreet id, sagittis sed lacus.",

  "Donec fringilla aliquet ligula, a faucibus purus fermentum in. Praesent lobortis molestie feugiat. Aenean sed dolor sit amet ligula porta egestas. Aliquam erat volutpat. Vestibulum aliquam rhoncus magna vitae pellentesque. In et pretium arcu. Vestibulum vel velit imperdiet, cursus sem et, ultrices sapien. In rutrum laoreet tortor at consequat. Integer posuere interdum pretium. Proin pellentesque suscipit mattis. Cras magna ante, sodales eu arcu nec, faucibus dignissim nibh. Nam ac lacus enim. Suspendisse quam felis, bibendum vitae euismod eu, luctus at arcu.",

  "Ut blandit turpis nec pellentesque ullamcorper. Pellentesque lacinia odio ac velit scelerisque, eget dapibus nulla lacinia. Aliquam consectetur, nunc rhoncus interdum rutrum, urna elit sollicitudin eros, eu volutpat metus ex vel lectus. Aenean ac libero sodales, imperdiet magna in, vestibulum nisi. Aenean viverra ante non elit porta sagittis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis lacinia nisl sit amet justo porttitor auctor. In mattis porta molestie. Duis id erat mauris. Suspendisse potenti. Pellentesque dictum libero sed purus pretium ullamcorper. Sed maximus finibus quam, vel accumsan leo commodo ac. Nulla facilisi.",

  "Ut sed ipsum eget velit aliquet commodo eget sit amet arcu. Curabitur sodales dui eros, vitae fermentum risus volutpat eget. Sed venenatis magna auctor est auctor, vitae faucibus enim tempus. Nulla pharetra urna vel consectetur dictum. Ut tincidunt orci a felis vulputate, in convallis libero iaculis. Maecenas vel neque mauris. Phasellus nec leo sed erat eleifend malesuada quis eu purus. Aenean a nisl augue. Donec ligula sapien, dapibus ac scelerisque quis, dapibus in ligula.",

  "Curabitur eget sem pharetra, pellentesque felis ut, tincidunt ligula. Mauris id justo laoreet, tincidunt mauris vel, gravida libero. Fusce vehicula massa et nisi consequat, ac hendrerit turpis finibus. Nullam rutrum tincidunt tortor eget ullamcorper. Integer egestas risus et gravida viverra. Proin pharetra nunc nisi, eget sollicitudin augue rutrum et. Donec ornare tortor quis commodo rutrum. Donec eu pellentesque libero. In euismod sem id imperdiet luctus. Aenean condimentum sem augue, quis auctor leo ultricies vitae.",

  "Curabitur a consectetur elit, quis rhoncus odio. Sed est lorem, ornare non sapien pharetra, facilisis interdum arcu. Sed aliquet ex nec tortor convallis egestas. Integer magna eros, convallis vitae ligula ac, placerat viverra turpis. Duis ultrices vehicula diam vel tempus. Donec et vulputate nisl. Nunc eu commodo turpis. Quisque pulvinar dui nec lacus gravida, quis facilisis sem placerat.",

  "Fusce non tellus non diam iaculis rutrum euismod in est. Mauris suscipit vitae justo eu interdum. Quisque accumsan malesuada tincidunt. Proin scelerisque, massa a sollicitudin sodales, ligula mi mattis diam, at tristique neque diam in ante. Nullam magna tellus, tincidunt blandit varius in, sodales sit amet dolor. Morbi cursus est lacus, at euismod mauris imperdiet vitae. Vivamus tincidunt eget arcu ornare volutpat. Nullam sed libero neque. Ut dictum ex non velit egestas rhoncus. Nunc imperdiet elit vitae mi aliquam, a consequat ante ultrices. Phasellus eleifend, odio at finibus eleifend, lacus erat eleifend ipsum, vel tristique nisi sem in eros. Nulla pulvinar gravida ante quis accumsan.",

  ",Phasellus lobortis odio vitae quam placerat tempor. Nullam tempus in augue sit amet gravida. Suspendisse posuere, erat et iaculis tristique, erat mi varius neque, non placerat erat libero nec lacus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vivamus sagittis diam massa, non rutrum massa convallis eget. Etiam est tellus, lacinia et mattis in, varius consequat libero. Fusce tincidunt dictum orci, quis vehicula augue placerat non. Phasellus mattis scelerisque ante, scelerisque lobortis ipsum congue a. Nunc dignissim orci lacus, in convallis orci feugiat ac. Morbi magna eros, posuere in dolor cursus, varius pretium tortor. Vivamus tincidunt pulvinar orci, non venenatis mi fringilla vel. Curabitur molestie euismod velit, vitae feugiat enim dictum sit amet. Pellentesque sed maximus sem. Phasellus viverra, quam ut condimentum vulputate, mauris leo suscipit lorem, in vehicula mauris nunc tempor dui. Donec elit elit, porta eu sollicitudin vel, venenatis feugiat purus.",

  "Nulla rhoncus metus non enim pretium, vel imperdiet arcu ultricies. Proin faucibus fringilla ornare. Nulla facilisi. Duis lacinia diam eros, non viverra quam accumsan in. Suspendisse vitae ex suscipit, rhoncus nisi eget, posuere sapien. Aenean consequat nunc ut feugiat aliquam. Phasellus odio turpis, lacinia id mollis vel, consequat et ex. Donec vel posuere risus. Nulla id purus eget lacus rhoncus convallis. Morbi mollis faucibus consectetur. Curabitur mollis quis magna id blandit. Ut varius fermentum vestibulum.",

  "Fusce odio sapien, venenatis quis bibendum sit amet, maximus vel urna. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nunc in egestas velit. Nulla aliquet eleifend nisl, vel consectetur nisi dignissim vitae. In ligula mauris, feugiat sit amet nulla id, consequat gravida urna. Nunc turpis velit, eleifend et velit vel, tempus faucibus nunc. Cras porta velit vitae lorem luctus, ultrices iaculis leo commodo. Donec tempor tempor velit, ut posuere arcu malesuada sit amet. In tincidunt ornare sodales. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Pellentesque eget viverra leo. Integer a feugiat augue. Sed pulvinar auctor placerat.",

  "Sed ipsum nibh, egestas non sodales ac, sagittis ac justo. Etiam vestibulum nisi ac consequat scelerisque. Duis sed leo vel urna dictum cursus. Aliquam elementum tellus eu quam rutrum semper. Nulla ligula urna, pellentesque vel vestibulum a, aliquam ut lorem. Pellentesque nunc leo, molestie quis sapien quis, volutpat fermentum sapien. Proin diam urna, sollicitudin rutrum elementum nec, convallis eget felis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Integer ligula leo, tempor ut convallis id, pretium at arcu. Suspendisse potenti. Nulla placerat gravida lacus, ac rhoncus sem varius in. Nullam at neque hendrerit, bibendum mauris ut, vestibulum lectus. Mauris porta rhoncus sem a aliquam. Sed pretium nibh quis tempor scelerisque. Nam quis magna diam.",

  "Duis vel magna et diam sollicitudin auctor. Sed purus nunc, laoreet eget pellentesque a, vehicula et risus. Aenean magna dolor, ornare eget semper ac, pharetra imperdiet augue. Suspendisse potenti. Fusce commodo, sapien in pretium feugiat, justo ex scelerisque erat, vel fermentum nulla diam eget lectus. Sed ornare, neque ut malesuada aliquet, libero elit laoreet leo, id laoreet nisl tellus eget sem. Aliquam cursus auctor ligula eu posuere. Ut in suscipit eros, a molestie erat. Sed hendrerit, sapien eu blandit malesuada, dolor dolor finibus nunc, in semper ante augue at arcu. Nullam eleifend a nunc vel sodales.",

  "Quisque ut eros nec nibh semper cursus in accumsan lorem. Vestibulum varius ante a metus aliquet volutpat. Morbi convallis libero malesuada porta lacinia. Proin id auctor libero. Proin odio elit, pellentesque sit amet est in, cursus hendrerit neque. Sed eget nisl mattis, suscipit nisi non, rhoncus augue. Cras pulvinar consectetur odio.",

  "Ut dictum ante est, quis bibendum orci rhoncus id. Sed finibus tortor id metus semper, nec porta arcu ornare. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse cursus tincidunt auctor. Cras non fringilla eros. Fusce ac ultricies quam. Aliquam tempor euismod porttitor. Donec faucibus est risus, vel accumsan arcu fermentum a. Suspendisse quam nulla, tincidunt vulputate felis in, mattis consectetur quam. Morbi scelerisque, neque a consequat fringilla, arcu neque fringilla neque, in dignissim libero massa in mauris. Nam vulputate elit nec mauris tempor, id interdum purus vulputate. Nulla eu aliquam risus, eu ornare ipsum. Nullam semper justo ut sapien eleifend pulvinar non ac magna. Pellentesque dui ante, iaculis quis pulvinar id, rutrum eget est. Aliquam erat volutpat.",

  "Proin velit sapien, scelerisque sed justo in, congue ullamcorper nisi. Nullam facilisis, velit non sagittis imperdiet, magna orci dictum diam, a efficitur est leo eget odio. Praesent fringilla justo a ipsum blandit, ut tempor sapien maximus. Integer rutrum justo in mi condimentum, in aliquam sapien vulputate. Vivamus nec turpis ac enim dictum finibus in sit amet enim. Ut in pretium tellus, cursus sagittis erat. Donec sagittis pretium mi, eget scelerisque dui consectetur non. Phasellus varius, tortor vel tempus egestas, lorem quam lobortis leo, id semper eros nisi sed diam. Vestibulum pellentesque orci quis tortor feugiat, ut ultricies mauris feugiat. Ut venenatis cursus urna sit amet rhoncus. Quisque pellentesque fringilla consequat.",

  "Maecenas euismod tristique orci, ut pretium arcu vehicula eu. Sed a quam eleifend arcu pharetra aliquam. Mauris vehicula feugiat metus, ut elementum arcu lobortis non. Sed maximus est in erat laoreet, eget tempor massa euismod. Aenean ullamcorper, sem in molestie suscipit, elit lorem cursus ante, interdum posuere dui leo sit amet nulla. Aenean gravida magna quis eros bibendum, in pellentesque leo varius. Nunc condimentum mi vestibulum metus ultrices, sit amet sollicitudin dui eleifend. Nunc sem libero, aliquet mattis enim in, fringilla auctor velit. Aenean accumsan sem neque, eu porttitor ligula cursus cursus. Donec iaculis feugiat eros ac maximus. Proin convallis efficitur leo, id lacinia nunc laoreet eu. Nam lacinia, sapien et facilisis pellentesque, magna sem vehicula nisi, vel porta ipsum orci at sem.",

  "Proin sodales id magna ac sodales. In viverra sem eu augue sagittis, quis molestie ligula pellentesque. Vivamus vitae nisi sed justo pharetra dapibus. Nam accumsan ut quam in euismod. Praesent lacus sapien, placerat ac pharetra id, euismod vitae ex. Aenean mollis orci dui, ut venenatis felis tempus vitae. Cras id ex sit amet turpis aliquam interdum eget eu augue. Sed at ultricies leo. Integer odio massa, luctus vitae varius ac, faucibus a orci. Praesent gravida posuere metus sollicitudin sollicitudin. Pellentesque cursus felis eget faucibus egestas. Praesent faucibus tristique est sed posuere.",

  "Praesent vel dictum ligula, faucibus facilisis nunc. Integer vitae ligula porttitor, volutpat lacus ut, maximus nisi. Vestibulum maximus sapien felis, in faucibus arcu placerat sed. Donec aliquet sed dui suscipit tincidunt. Nullam pellentesque odio quis tortor pellentesque, ut blandit turpis ultricies. Integer suscipit erat magna, vel hendrerit enim tincidunt sed. Nulla vitae leo eu ex tempus cursus a ut est. Cras nec semper nulla, a scelerisque est. Etiam eget semper massa. Vestibulum rutrum luctus magna sed viverra. Aliquam eget hendrerit lacus. Phasellus tempus non lectus sed vulputate.",

  "Cras arcu eros, condimentum ut ex eget, dapibus pulvinar mi. Donec egestas sagittis nisi, malesuada gravida magna fermentum nec. Duis condimentum lacinia sodales. Nullam id convallis urna, id congue elit. Nullam in mi urna. Integer dapibus commodo massa pharetra molestie. Duis at fringilla dui. Suspendisse potenti.",

  "Proin nec sodales sapien. Mauris id quam commodo, consectetur mauris sit amet, pretium arcu. Quisque nec lacus tortor. Vestibulum justo purus, euismod sed dolor vel, venenatis commodo turpis. Pellentesque ac tempor mi, eu rhoncus turpis. Donec pretium nec diam sit amet volutpat. Nunc tincidunt sit amet diam eget varius. Donec finibus ligula vitae elit pulvinar scelerisque. Nullam posuere lacinia hendrerit. Nullam sapien lorem, ornare quis dui ac, maximus molestie libero. Aliquam leo ex, rhoncus ut interdum et, blandit quis massa. Sed interdum lacinia sapien at consectetur. Cras at gravida nunc, sed ullamcorper nisl. Pellentesque iaculis congue hendrerit.",

  "Suspendisse nisi ligula, venenatis ultrices enim at, tempor cursus magna. Aenean convallis, nibh ac ornare porttitor, dui ipsum rutrum erat, a viverra justo ex eu mi. Aliquam bibendum fringilla ex ac laoreet. Aliquam sagittis placerat iaculis. Phasellus sed interdum sapien. Pellentesque eros dolor, dignissim at turpis pretium, tincidunt aliquam sem. Sed vitae tincidunt neque. Pellentesque blandit dolor accumsan turpis lacinia suscipit. Vivamus sapien turpis, elementum ut dolor sit amet, tristique malesuada velit. Sed eget nulla et eros blandit consequat. Nulla sit amet sem ipsum. Pellentesque sagittis ipsum at ex feugiat laoreet. Suspendisse turpis diam, ornare et dui pulvinar, iaculis sodales nisl. Suspendisse quis volutpat elit.",

  "Etiam in ipsum convallis, convallis mi id, euismod tortor. In condimentum consequat lacus non congue. Aenean magna eros, hendrerit ut ipsum sed, dapibus feugiat lectus. Donec suscipit ornare hendrerit. Phasellus metus orci, feugiat a tortor ac, iaculis consectetur turpis. Nunc at ipsum sit amet odio posuere venenatis non quis erat. Vestibulum et tellus vitae eros ultrices rhoncus et ac velit. Suspendisse at nisi suscipit, accumsan ipsum ac, iaculis enim. Donec quam justo, viverra sed nunc eget, auctor aliquet elit. Etiam faucibus dictum gravida. Vestibulum pellentesque massa tempus ex luctus tempor sed at purus. Morbi vulputate quam nunc, sit amet fringilla urna semper sed. Curabitur dignissim tortor sit amet justo tristique sollicitudin.",

  "Donec in mauris leo. Phasellus eget tortor eget ligula commodo mollis vitae et massa. Praesent maximus nisi justo, at cursus risus pellentesque id. In suscipit lacus quis auctor vestibulum. In accumsan sodales ex at fringilla. Integer vestibulum laoreet lacinia. Fusce scelerisque leo augue, fermentum molestie sapien rutrum ut. Fusce ultricies sodales velit, pellentesque commodo erat pulvinar eu. Donec molestie, tortor nec tempor imperdiet, ipsum tellus accumsan elit, vel ultricies arcu lacus ut urna. Cras tincidunt, nunc quis bibendum maximus, justo risus lacinia massa, sit amet tincidunt elit neque sit amet nisl.",

  "Curabitur feugiat ultricies lectus, vel laoreet tortor lobortis sodales. Aliquam lobortis tincidunt lectus ac finibus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aliquam erat volutpat. Cras sit amet egestas elit. In congue interdum metus, vel elementum lacus maximus ut. Integer ultricies pretium sapien et feugiat. Ut in arcu vitae urna feugiat pulvinar. Quisque non dolor ut magna egestas sodales nec eget elit. Quisque accumsan lacus vel nisi porta, ut eleifend turpis volutpat. Suspendisse potenti. Quisque eu sapien augue. Maecenas sit amet varius enim, id ornare metus. Quisque ultricies eros sit amet rutrum sagittis. Cras neque neque, congue vitae velit vitae, tincidunt vulputate turpis.",

  "Suspendisse leo nibh, blandit vitae est vitae, tincidunt hendrerit est. Ut laoreet, diam eu hendrerit pretium, ante lectus consequat quam, ut hendrerit ante quam in metus. In hac habitasse platea dictumst. Sed viverra sagittis mauris malesuada ultricies. Etiam id urna odio. Phasellus vehicula velit in eros sollicitudin, id cursus erat molestie. Integer aliquet lacus porttitor, efficitur mi vel, ultrices ipsum.",

  "Morbi vulputate pharetra mauris, sed tincidunt turpis. Nam tincidunt eros mauris, sed sagittis orci bibendum non. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Fusce tincidunt ante nec velit sollicitudin, vel faucibus odio gravida. Sed sit amet risus nunc. Nulla sit amet mauris mauris. Morbi faucibus commodo tellus, ac fermentum sapien tincidunt in. Sed nisl nunc, sollicitudin commodo viverra non, ornare non augue. Cras rutrum vehicula ipsum eu mattis. Nam pretium enim vitae imperdiet bibendum. Pellentesque eget rutrum nibh, non convallis sapien. Vivamus euismod, sapien sed iaculis tempus, ante libero tincidunt risus, in facilisis ante quam ac odio. Curabitur tempus eu urna quis tincidunt. Cras blandit sollicitudin velit, eget pellentesque arcu maximus vel. Sed pellentesque elit sed turpis dapibus, vitae dapibus justo facilisis.",

  "Vestibulum et malesuada ipsum. Suspendisse vel blandit purus. In odio ex, ultricies a finibus ac, tincidunt quis leo. Nullam ante velit, aliquet quis scelerisque vitae, vehicula at magna. Proin vulputate lorem est, a fringilla nunc fermentum ac. Etiam volutpat tellus ac arcu ultrices iaculis. Duis faucibus nunc id dui luctus, sed suscipit erat vulputate. Duis congue sapien eget tincidunt tincidunt. Aliquam erat volutpat. Cras imperdiet est quis pulvinar aliquet. Nam ac fringilla neque.",

  "Maecenas malesuada elit rhoncus, semper nisl in, rhoncus eros. Suspendisse vehicula metus sapien, ac consectetur quam consectetur non. Quisque eros tortor, mollis vel libero sed, efficitur pharetra quam. Nunc ante diam, consequat vitae convallis ac, facilisis in ex. Pellentesque laoreet rutrum tortor, vitae ultricies ligula rutrum at. Integer facilisis interdum laoreet. Sed porta ipsum sit amet ligula ultricies posuere vel tempus velit. Curabitur et blandit turpis. Suspendisse fermentum at augue sit amet blandit. Morbi et sapien nunc. Phasellus sed enim et purus vehicula interdum eget nec sem. Nulla sollicitudin maximus nisi. Vestibulum faucibus elit a mauris maximus finibus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin eu fermentum justo.",

  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sed pellentesque tortor. Sed tincidunt nisl sed felis interdum interdum. Nulla id nibh iaculis, laoreet diam a, scelerisque elit. Nullam hendrerit venenatis velit non convallis. Maecenas ut maximus massa, at facilisis nisi. Praesent vel euismod lorem. Ut dictum pharetra interdum.",

  "Pellentesque sit amet sagittis leo. Nulla efficitur, tortor at rhoncus aliquet, libero nunc vulputate neque, id pellentesque augue nunc id eros. Praesent malesuada id nisi vitae ullamcorper. Curabitur ornare imperdiet est, sed auctor augue malesuada vel. Integer luctus tempor pulvinar. Quisque pretium massa vitae sem maximus vehicula. Fusce convallis, diam et tempor tincidunt, ante lacus sollicitudin dolor, at consectetur erat enim ac purus. Donec et odio ac turpis efficitur eleifend. Pellentesque at metus massa.",

  "Aliquam molestie nunc eros, eu maximus est tempus eget. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Maecenas malesuada erat at egestas mattis. Praesent dignissim ornare purus, sed convallis dui euismod et. Curabitur sit amet dignissim massa. Maecenas sagittis, diam ac vestibulum sagittis, tortor purus vehicula metus, nec pharetra nulla nisi in magna. In porttitor tortor sit amet ipsum tempor ultricies. Nulla convallis risus a libero commodo molestie. Pellentesque ullamcorper velit et mollis interdum. Pellentesque non bibendum nibh. In ipsum metus, commodo nec accumsan vel, blandit vitae dolor. Quisque vestibulum, sem ut malesuada consequat, ex ipsum egestas lorem, vel dictum arcu nunc ultricies leo. Proin ac leo quis magna tempor scelerisque ut non arcu. Praesent posuere, risus sit amet accumsan mattis, massa orci posuere felis, ut luctus tortor nisi nec elit. Suspendisse nisi libero, vulputate ut tempus quis, posuere at odio.",

  "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Curabitur eget massa eu diam varius commodo. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum ullamcorper nec lacus a ultricies. Aenean feugiat, lacus sit amet facilisis vulputate, massa sapien scelerisque quam, semper varius enim odio nec neque. Duis et tellus eget nisl maximus porttitor et eu ipsum. Ut ornare accumsan sapien nec tincidunt. Suspendisse enim felis, suscipit sit amet sem et, vulputate congue lectus. Quisque nec mauris urna. Ut pulvinar orci ut lectus accumsan ullamcorper. Pellentesque enim odio, fermentum sit amet velit in, varius accumsan ligula. Vivamus vitae interdum turpis. Suspendisse potenti. Nullam vitae porta nulla.",

  "Vivamus vehicula neque eu leo gravida, eu molestie neque cursus. Nam nec felis purus. Morbi volutpat tempor libero, a posuere magna faucibus ac. Quisque consequat semper purus, a varius elit ultricies eu. In at turpis finibus, dapibus nisi quis, vehicula elit. Curabitur congue nisi metus. Phasellus mollis consequat nibh at gravida. Duis vestibulum commodo lectus sed pulvinar. Sed tristique nisl at vestibulum commodo. In tempor, ligula nec ullamcorper dignissim, sapien ligula bibendum eros, in convallis arcu lorem et magna. Integer id lacus commodo, scelerisque libero id, tristique neque. Aliquam vestibulum molestie finibus. Sed hendrerit fermentum ornare. Donec sit amet neque sit amet quam efficitur pretium sed quis neque. Nullam vel lacus tempus, molestie eros vitae, suscipit lacus. Suspendisse porta dui eget efficitur volutpat.",

  "Sed consectetur ipsum et imperdiet dictum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce at nulla at velit lobortis aliquam quis vitae quam. Donec sit amet ipsum dignissim, ultricies tellus finibus, suscipit erat. Sed bibendum nisl lectus, at efficitur sapien sollicitudin eu. Aenean sit amet mi a neque condimentum accumsan eget vitae risus. Suspendisse potenti. Suspendisse dictum facilisis tristique. Cras sit amet tincidunt arcu.",

  " Donec felis odio, pretium vitae tristique ac, interdum in dolor. Etiam accumsan dictum diam, sed egestas ex lobortis sed. Fusce ut tristique enim. Suspendisse potenti. Fusce pellentesque suscipit urna, eu imperdiet augue interdum et. Suspendisse convallis scelerisque lorem et accumsan. Nullam viverra, nisi sed malesuada tincidunt, massa nibh commodo quam, sit amet ultricies ex urna sed turpis. Fusce id convallis diam. Sed fermentum, elit et mattis lobortis, velit nibh efficitur nisl, et ultrices turpis odio non nulla. Fusce lobortis, nisi sit amet vulputate fermentum, tellus sem vestibulum libero, ut ultrices sapien ante pretium risus. Aliquam cursus varius ligula, quis tristique leo placerat a. Donec id dapibus ex. Nulla.",
];

console.log(text.length);

let item = document.querySelector("#item");
let dataContainer = document.querySelector("#data-container");

function generate() {
  console.log(item.value);
  if (isNaN == item.value || item.value < 0 || item.value > 54) {
    // data.innerHTML = `<p>${text[Math.floor(Math.random() * text.length)]}</p>`;
    alert("Please enter the number below 55");
  } else {
    const count = parseInt(item.value); // Convert user input to an integer
    const selectedText = text.slice(0, count); // Select the desired number of paragraphs

    const paragraphs = selectedText.map((d) => {
      return `<p>${d}</p>`;
    });
    dataContainer.innerHTML = paragraphs.join("");
  }
}
